### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by ixayldz** [D4rKDeagle/csgo-matchbot#1]
is it still working ?

**Comment by ixayldz** [comment]
why did u close man is it work not  ?

**Comment by D4rKDeagle** [comment]
Well since someone actually found this somehow, I should probably put out here that I'm not actively working on this. This is currently a side project, as I have more important stuff to work on right now. If I ever get around to doing this properly, I'll reboot the project, as it is still on my bucket list. Until then, you may consider this temporarily dead.

**Comment by ixayldz** [comment]
mr dark. listen i am from turkey. we cant play eu gameservers because of
ping. i buy dedicated and i created 5 game server.

i just want people go website find match. or if they play premade create
loby find match and go gameserver. when they go 10 player game server than
match start. and get stats match. thats all i dont want very complex
website everything can be basic. login with steam and play thats all like
popflash pls we need this.plsss dark

2016-02-16 0:13 GMT+02:00 D4rKDeagle <notifications@github.com>:
